config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :authors do
    resources :books
  end

  get '/books', to: 'books#books_list'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :supplier
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
	
	validates :name, presence: true
	has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
	# validates :title, presence: true, if: :title_is?

	validates :title, length: {minimum: 2}
	validates :description, length:{maximum: 100}
	# validates :description, length: { within: 2...20 }
	# validates :title, length: {minimum: 2}
	# validates :title, length: { maximum: 2 }
	 # validates :title, length: { in: 2..5 }
	  # validates :title, length: { in: 5 }
	#validates :title, length:{is: 5}, message: "%{value} must be five characters."}, on: :create
	  # def title_is?
	  # 	title == 'sri'
	  # end
	# validates :title, length: {minimum: 2}, allow_blank: true
	# validates :title, exclusion: {in: %w(www ca us jp), message: "%{value} is reserved"}
	# validates :title, length: {minimum: 2}, allow_nil: true
		
	#...............<CALLBACKS>.................
	after_validation :check_title?
	before_validation :description_has_value?, on: :create 
	belongs_to :author
	#after_create_commit :log_user_saved_to_db
	# before_save :another_name_field_has_value?
	private
		def check_title?
			self.title = "MMM" if title == "SSS"
		end

		def description_has_value?
			self.description = "hellooooooooooooooo" unless description.present?
		end

		# def self.another_name_field_has_value?
		# 	ano_name = "RRR" if ano_name.blank?
		# end

		# def log_user_saved_to_db
		#     puts 'Book was saved to database'
		# end

end

app/models/mymouse.rb
class Mymouse < ApplicationRecord
  scope :search, -> { where(created_at: Time.now) }
end
 

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_one :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all
	end

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		if @author.save
			flash[:notice] = 'Successfully created'
			redirect_to authors_path
		else
			flash[:notice] = 'Failed to create'
			redirect_to authors_path
		end
	end

	def show
		@author = Author.find(params[:id])
		respond_to do |format|
      format.js	
    end
	end

	def edit
		@author = Author.find(params[:id])
		respond_to do |format|
      format.js	
    end
	end

	def update
		@author = Author.find(params[:id])
		if @author.update(author_params)
			flash[:notice] = 'Successfully updated'
			redirect_to authors_path	
		else
			flash[:notice] = 'Failed to update'
			redirect_to authors_path	
		end
	end

	def destroy
		@author = Author.find(params[:id])
		@author.destroy

		redirect_to authors_path
	end

	def destroy
	  @author = Author.find(params[:id])
	  @author.destroy
	 
	  redirect_to authors_path
	end

	private
		def author_params 
			params.require(:author).permit(:name)
		end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def books_list
    @books = Book.all
  end

  def index
  	@books = author.books.all
  end

  def new
  	@book = author.books.new
  end

  def create
  	@book = author.books.new(book_params)
  	if @book.save
  		redirect_to author_books_path
  	else
  		render 'new'
  	end		
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to author_books_path
  	else
  		render 'edit'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def show
  	@book = Book.find(params[:id])
    respond_to do | format |
      format.js
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy

  	redirect_to author_books_path
  end

  private
  	def book_params
  		params.require(:book).permit(:title, :description,:author_id)
  	end

  	def author
  		Author.find(params[:author_id])
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%=form_for @author do |form|%>
  <div class="modal-header">
    <h5 class="modal-title" id="AuthorModalLabel">New message</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
		<div class="form-group ">	
				<b><%= form.label :name, class: "col-form-label"%></b>
				<%= form.text_field :name, class: "form-control"%><br>
		</div >
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= form.submit 'Submit', class: "btn btn-primary btn-sm", role:"button"%>
  </div>
<%end%>

app/views/authors/edit.html.erb
<h3 style="margin-top: 30px;margin-bottom: 20px">Edit Author</h3>
<%= render 'form' %>

app/views/authors/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'authors/form') %>");
$("#modal-window").modal();
console.log('edit render completed.....');

app/views/authors/edit_author.html.erb
<h3 style="margin-top: 30px;margin-bottom: 20px">Edit Author</h3>
<%= render 'form' %>

app/views/authors/index.html.erb
<div class="container">
    <!-- <div id="error_explanation" class="alert alert-primary" role="alert" style="width: 40rem">
      <h5>
        Errors
      </h5>
      <ul>
        <%# @author.errors.full_messages.each do |msg| %>
          <li><%#= msg %></li>
        <%# end %>
      </ul>
    </div> -->
    <%if flash[:notice].present? %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong> <%= flash[:notice] %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <%end%>
    <div class="row col-md-20">
    	<h3 style="margin-top: 30px; margin-bottom: 20px">List of Authors</h3>
		<table class="table table-hover table-bordered table-striped ">
			<%if @authors.present?%>
			<thead class="thead-dark">
				<tr>
					<th scope="col">Author Name</th>	
					<th scope="col">Number of books</th>
					<th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				<%@authors.each do |author|%>
					<tr>
						<td>
							<%= author.name%>
						</td>
						<td>
							<%=author.books.size%>
						</td>
						<td>
							<%= link_to "Edit", edit_author_path(author),class: "btn btn-primary btn-sm", role: "button", remote: true%>&nbsp
							<%= link_to "Show", author_path(author), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-sm'} %>&nbsp
							<%= link_to "Add Book", new_author_book_path(author),class: "btn btn-primary btn-sm", role: "button" %>&nbsp
							<%= link_to "Books List", author_books_path(author),class: "btn btn-primary btn-sm", role: "button" %>&nbsp
							<%= link_to "Destroy", author_path(author), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm", role: "button"	%>&nbsp
						</td>
					</tr>
				<%end%>
			<%else%>
				<tr><td> There is no authors to display.</td></tr>
			<%end%>
			</tbody>

		</table>
		<%= link_to 'New Author', new_author_path, class: "btn btn-primary btn-sm", role: "button", remote: true %>
	</div>
</div>


</div>
<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="modal-windowTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      
    </div>
  </div>
</div>

<div class="modal fade" id="AuthorModal" tabindex="-1" role="dialog" aria-labelledby="AuthorModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<h3 style="margin-top: 30px; margin-bottom: 20px" >New Author</h3>
<%= render 'form' %>

app/views/authors/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'authors/form') %>");
$("#modal-window").modal();
console.log('new method rendering completed.....');

app/views/authors/newAuthor.html.erb
<h3 style="margin-top: 30px; margin-bottom: 20px" >New Author</h3>
<%= render 'form' %>

app/views/authors/partials/_modal.html.erb
      <%@author = Author.find(params[:id])%>
      <%if @author.present? %>
      <div class="modal-header">
        <h5 class="modal-title" id="modal-windowTitle">Author Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>
            <strong>Name:</strong>
            <%= @author.name %>
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <% end %>

app/views/authors/show.html.erb
<h2>Author details</h2>
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>
<p>
	<%= link_to "Back", authors_path %>&nbsp
	<%= link_to "destroy", author_path, method: :delete, data: { confirm: 'Are you sure?' }%>
</p>

app/views/authors/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'authors/partials/modal') %>");
$("#modal-window").modal();

app/views/authors/shown.html.erb
<h2>Author details</h2>
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>
<p>
	<%= link_to "Back", authors_path %>&nbsp
	<%= link_to "destroy", author_path, method: :delete, data: { confirm: 'Are you sure?' }%>
</p>

app/views/books/_errors.html.erb
<% if @book.errors.any? %>
    <div class="alert alert-primary" role="alert" >
      <p>
        <%= pluralize(@book.errors.count, "error") %>
      </p>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/books/_form.html.erb
<%=form_for @book, url: {action: (params[:action]=='new' || params[:action]=='create') ? 'create' : 'update' }, class: 'form-horizantal' do |form|%>
	<%= render 'books/errors' %>
	<div class="form-group">
		<div class="col-md-2">
			<strong><%= form.label :title%></strong>
			<%= form.text_field :title, class: 'form-control'%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2">
			<strong><%= form.label :description%></strong>
			<%= form.text_area :description, class: 'form-control', style: 'width: 100%'%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-2">
			<%= form.submit 'Submit', class: 'btn btn-primary btn-sm', role: "button"%>
		</div>
	</div>
<%end%>

app/views/books/_modal.html.erb
      <%@book = Book.find(params[:id])%>
      <%if @book.present? %>
      <div class="modal-header">
        <h5 class="modal-title" id="modal-windowTitle">Book Details</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>
            <b>Title:</b>
            <%= @book.title %>
          </p>
          <p>
            <b>Description:</b>
            <%= @book.description %>
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <% end %>

app/views/books/books_list.html.erb
<h2 style="margin-top: 30px;margin-bottom: 20px">List of books</h2>
<table class="table table-hover table-bordered table-striped " >
	<%if @books.present? %>
		 <thead class="thead-dark">	
			<tr>
				<th scope="col" >Book Name</th>
			</tr>
		</thead>
		<tbody>
			<%@books.each do |book|%>
				<tr>
					<td>
						<%= book.title%>
					</td>
				</tr>
			<%end%>
		</tbody>
	<%else%>
		<p> No books found. </p>
	<%end%>
</table>

app/views/books/edit.html.erb
<h3 style="margin-top: 30px;margin-bottom: 20px">Edit book details</h3>
<%= render 'books/form'%>

app/views/books/index.html.erb
<h2 style="margin-top: 30px;margin-bottom: 20pxs">List of books</h2>
<!-- <div  class="card" style="width: 60rem;">-->
<table class="table table-hover table-bordered table-striped " >
	<%if @books.present? %>
		 <thead class="thead-dark">	
			<tr>
				<th scope="col" >Book Name</th>
				<th scope="col" >Description</th>
				<th scope="col" >Actions</th>
			</tr>
		</thead>
		<tbody>
			<%@books.each do |book|%>
				<tr>
					<td>
						<%= book.title%>
					</td>
					<td>
						<%= book.description %>
					</td>
					<td>
						<div>
							<%= link_to "Edit", edit_author_book_path(id:book.id),class: "btn btn-primary btn-sm", role: "button" %>&nbsp &nbsp
						
							<%= link_to "Show", author_book_path(id:book.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-sm'} %>&nbsp &nbsp
						
							<%= link_to 'Destroy', author_book_path(id:book.id), method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-primary btn-sm", role: "button" %>
						</div>
					</td>
				</tr>
			<%end%>
		</tbody>
	<%else%>
		<p> No books found. </p>
	<%end%>
</table>
<%= link_to 'Back', authors_path, class: "btn btn-primary btn-sm", role: "button"%>
<%= link_to 'Add Book', new_author_book_path, class: "btn btn-primary btn-sm", role: "button"%>	
	
</div>
<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="modal-windowTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h3 style="margin-top: 30px;margin-bottom: 20px">Add Book</h3>
<%= render 'books/form' %>

app/views/books/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'books/modal') %>");
$("#modal-window").modal();

app/views/layouts/_nav_bar.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist" >
  <li class="nav-item">
    <%=link_to 'Authors', authors_path, class: "nav-link"%>
  </li>
  
  <li class="nav-item">
    <%=link_to 'books', books_path, class: "nav-link" %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>	
		<%=render 'layouts/nav_bar'%>
	</header>

	<main class="container">
		<%= yield %>
	</main>

	<footer class="footer">
		<div class="container">
			<span class="text-muted">@Devathon</span>
		</div>
	</footer>
</body>
</html>	

app/views/welcome/index.html.erb
<center><h2 style="margin-top: 30px">Welcome to Library</h2>
<%= link_to 'Add Author', new_author_path, class: "btn btn-primary btn-sm", role: "button", style:'margin-top:20px'%></center>
<!-- <button id="products">Ajax Ex</button>
<div class="container-fluid" >
  <div class="row giftCards-container-large" id="products_content">
  </div>
</div> -->
<!-- <script id="template" type="text/x-jquery-tmpl" >
      <div class="col-md-4 col-lg-4 col-sm-6 col-xs-6 giftCards-card-block">
        <div class="giftCards-img-merchandise-large">
          <div class="giftCards-div-container">
            <img class="img-responsive giftCards-img-card-large center-block" src="${url}">
          </div>
        </div>
        <h4 class="giftCards-productname giftcard-h4-xs" style="position: relative;top: 1px;margin-left: 5px">
          <a class="truncate-text-line-2" href="#">${name}</a>
        </h4>
        <div class="row" style="position: relative;top: -30px">
          <div uib-dropdown="" class="col-sm-4 col-md-3 col-lg-3 hidden-xs dropdown"  aria-hidden="false">
            <button class="btn btn-default buy-gift-amount dropdown-toggle"  style="height: 33px" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-inr"></i>Rs. 5000 <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" selected="selected">
              <li role="menuitem" ><a><i class="fa fa-inr"></i>Rs. 5000</a></li>
              <li role="menuitem" ><a><i class="fa fa-inr"></i>Rs. 500</a></li>
              <li role="menuitem" ><a><i class="fa fa-inr"></i>Rs. 1000</a></li>
              <li role="menuitem" ><a><i class="fa fa-inr"></i>Rs. 2000</a></li>
              <li role="menuitem" ><a><i class="fa fa-inr"></i>Rs. 1</a></li>
            </ul>
          </div>  
          <div class="col-sm-3 col-md-4 col-lg-4 hidden-xs btn-buyredeem-container-sm">
            <button class="btn giftCards-btn-buynow-large" style="position: relative;font-size: 11px;height: 33px;margin-left: 15px">BUY NOW</button>
          </div>
          <div class="col-sm-5 col-md-5 col-lg-5 hidden-xs">
            <button class="btn giftCards-btn-enquiry-large pull-right" style="font-size: 11px;height: 33px !important" >BULK ENQUIRY</button>
          </div>
        </div>
      </div>
</script> -->

<!-- <script type="text/javascript" >
  $(document).ready(function(){
      $("#products").on("click", function(event){
          $.ajax({
              url:"https://api.zaggle.in/api/v1/products/search",
              method: "GET",
              dataType: "json",
              success: function (result) {
                // console.log();
                $("#products_content").empty();
                for ( var i=0 ; i<result.products.length ; i++ ){
                    var product_data = {
                        name: result.products[i].name,
                        url: result.products[i].image.image.url
                    };
                    console.log(product_data);
                    var tbody=$("#template").tmpl(product_data);
                    $('#products_content').append(tbody);
                } 
              },
              error: function(){
                console.log("fail");
              }
          });     
      });
  });
</script> -->